Generates a training and a test set of 1, 000 points sampled uniformly in [0,1]x[0,1],

each with a
label 0 if outside the disk centered at (0.5, 0.5) of radius $1/√2π$, and 1 inside,

In [34]:
import math
import numpy as np
import torch
from torch import Tensor
1/(2*math.pi)

0.15915494309189535

that returns a pair torch.Tensor, torch.LongTensor of dimensions respectively nb×2 and nb,
corresponding to the input and target of a toy data-set where the input is uniformly distributed in
[−1, 1] × [−1, 1] and the label is 1 inside the disc of radius sqrt(2/pi)
and 0 outside.
Create a train and test set of 1, 000 samples, and normalize their mean and variance to 0 and 1.
A simple sanity check is to ensure that the two classes are balanced.


In [19]:
x = (Tensor(1000, 2).uniform_(0, 1))
print(x)

tensor([[0.2787, 0.4553],
        [0.4961, 0.1862],
        [0.6867, 0.1390],
        ...,
        [0.5503, 0.7721],
        [0.4663, 0.7550],
        [0.1482, 0.2287]])


In [39]:
print(x.sub(0.5))
y = (x.sub(0.5))
print(y.pow(2).sum(1)[1:10])
print((y.pow(2).sum(1)<(1/(2*math.pi)))[1:10].long())

tensor([[-0.2213, -0.0447],
        [-0.0039, -0.3138],
        [ 0.1867, -0.3610],
        ...,
        [ 0.0503,  0.2721],
        [-0.0337,  0.2550],
        [-0.3518, -0.2713]])
tensor([0.0985, 0.1652, 0.0045, 0.0095, 0.0455, 0.1706, 0.3207, 0.0637, 0.2696])
tensor([1, 0, 1, 1, 1, 0, 0, 1, 0])


In [35]:
0.0985-0.15915

-0.06065000000000001

In [53]:
#1 Toy Data-set
def generate_data():
    input1 = (Tensor(1000, 2).uniform_(0, 1))
    target = ((input1.sub(0.5)).pow(2).sum(1)<=(1/(2*math.pi))).long()
    return input1, target


In [46]:
input1, target = generate_data()
print(input1[0:10],target[0:10])

tensor([[0.0623, 0.8525],
        [0.0646, 0.4073],
        [0.1301, 0.6887],
        [0.0377, 0.4339],
        [0.6757, 0.7643],
        [0.6465, 0.3312],
        [0.5149, 0.0027],
        [0.3160, 0.7118],
        [0.6160, 0.8623],
        [0.4164, 0.5597]]) tensor([0, 0, 0, 0, 1, 1, 0, 1, 1, 1])


In [52]:
z = input1[4]-0.5
print(z)
z.pow(2)
print(z.pow(2).sum())

tensor([0.1757, 0.2643])
tensor(0.1007)
