In [1]:
import math
import torch
from torch import empty
import numpy as np
torch.set_grad_enabled(False)

In [26]:
M = torch.empty(5,3,dtype=float).normal_(0,1)
print(M.size())
print(M.dtype)
print(M)
x = torch.empty([5,1],dtype=float).normal_(0,1)
print(x)
print(x.t().mm(M))

torch.Size([5, 3])
torch.float64
tensor([[ 1.4316,  1.3041,  0.5361],
        [-1.2588, -0.4268, -0.9840],
        [-0.9309,  0.6688, -1.0878],
        [-1.3049, -1.3529, -0.0602],
        [-0.7150,  1.0859,  0.6840]], dtype=torch.float64)
tensor([[ 1.4177],
        [ 1.4022],
        [ 0.4705],
        [ 0.0183],
        [-0.0564]], dtype=torch.float64)
tensor([[-0.1569,  1.4790, -1.1713]], dtype=torch.float64)


In [32]:
test = torch.empty(3,1)
print(test)
print(torch.zeros(3,1).type())
print(torch.zeros(3))
print(torch.zeros(3,1))

tensor([[ 0.0000e+00],
        [ 0.0000e+00],
        [-2.1604e+16]])
torch.FloatTensor
tensor([0., 0., 0.])
tensor([[0.],
        [0.],
        [0.]])


In [1]:
class Module() :
    def __init__(self):
        #???
        
    def forward(self, *input):
        raise NotImplementedError
    def backward(self,*gradwrtoutput):
        raise NotImplementedError
    def param(self):
        return []
    def zero_grad(self):
        raise NotImplementedError

class Linear(Module):
    """
        One fully connected layer.
        Input : input_dimension, output_dimension [int]
        Those corresponds to the numbers of nodes in a given input layer
        and the number of nodes in the output layer
        Weights and Bias are initialized using the Xavier initialization
        see course 5.5 slide 14 (What is the gain here??)
    """
    def __init__(self,in_dim,out_dim):
        self.in_dim = in_dim
        self.out_dim = out_dim
        std = math.sqrt(2./(in_dim+out_dim))
        self.w = torch.empty(out_dim,in_dim).normal_(0,std)
        self.b = torch.empty(out_dim,1).normal_(0,std)
        self.dw = torch.zeros(out_dim,in_dim)
        self.db = torch.zeros(out_dim,1)
    
    """
        Function to set grad to zero. Used in gradient step
    """
    def zero_grad(self):
        self.dw.zero_()
        self.db.zero_()
    """
        results of FW pass of layer, returns s = x*w + b
        using formula from Practical 03
    """
    def forward(self,x):
        return self.w.mv(x.view(-1))+self.b
    
    """
        Backward pass, see practical 03
    """
    def backward(self,x):
        WRITE STUFF Here
        
#ACTIVATION FUNCTIONS
class ReLU(Module):
    """
    ...
    """
    def __init__(self):
        Module.__init__(self)
    
    def forward(self,x):
        return np.maximum(0,x)
    
    def backward(self,x,dl_dx):
        ??

class tanh(Module):
    
    def __init__(self):
        Module.__init__(self)
        
    def forward(self,x):
        return x.tanh()
    
    def backward(self,x,dl_dx):
        return dl_dx/ (torch.pow(torch.cosh(x),2))
        
        
#LOSS         
class MSEloss(Module):
    """ SEE PRACTICAL 03 UPDATE DOC LATER"""
    def __init__(self):
        Module.__init__(self)
     
    """
    """
    def forward(self,x,t):
        return (x - t).pow(2).sum()
    
    def backward(self, x, t):
        return 2 * (x - t)
    # MAYBEWRONG UPDATE THIS LATER
    

        
