In [1]:
import torch
import numpy as np
import math

In [29]:
x = torch.empty(10).normal_(0,5)
print(x)
b = torch.max(x,torch.zeros(x.size()))
print(b)

tensor([ -7.6634,   5.5474, -12.4726,  17.2371,  -3.4655,   3.4737,   0.6242,
        -11.0671,  -6.5717,   5.9690])
tensor([ 0.0000,  5.5474,  0.0000, 17.2371,  0.0000,  3.4737,  0.6242,  0.0000,
         0.0000,  5.9690])


In [24]:
print(x.max())
print(x-x.max())

tensor(12.1670)
tensor([-14.5231, -14.7825,  -4.0445,  -8.0057, -15.0185, -13.6187, -12.0864,
        -27.9149, -15.4833,   0.0000])


In [30]:
y = torch.exp(x)
x1 = x-x.max()
print("x",x)
print("y",y)
print("ysum",y.sum())
print("ySoftmax", y/(y.sum()))
z = torch.exp(x1)

print("---------------")
print("x1",x1)
print("z",z)
print("zsum",z.sum())
print("zsoftmax",z/(z.sum()))

x tensor([ -7.6634,   5.5474, -12.4726,  17.2371,  -3.4655,   3.4737,   0.6242,
        -11.0671,  -6.5717,   5.9690])
y tensor([4.6968e-04, 2.5658e+02, 3.8300e-06, 3.0619e+07, 3.1256e-02, 3.2257e+01,
        1.8668e+00, 1.5618e-05, 1.3995e-03, 3.9112e+02])
ysum tensor(30619794.)
ySoftmax tensor([1.5339e-11, 8.3795e-06, 1.2508e-13, 9.9998e-01, 1.0208e-09, 1.0535e-06,
        6.0966e-08, 5.1005e-13, 4.5704e-11, 1.2774e-05])
---------------
x1 tensor([-24.9006, -11.6897, -29.7098,   0.0000, -20.7027, -13.7634, -16.6129,
        -28.3042, -23.8088, -11.2681])
z tensor([1.5340e-11, 8.3797e-06, 1.2509e-13, 1.0000e+00, 1.0208e-09, 1.0535e-06,
        6.0967e-08, 5.1006e-13, 4.5705e-11, 1.2774e-05])
zsum tensor(1.0000)
zsoftmax tensor([1.5339e-11, 8.3795e-06, 1.2508e-13, 9.9998e-01, 1.0208e-09, 1.0535e-06,
        6.0966e-08, 5.1005e-13, 4.5704e-11, 1.2774e-05])


30618041.968912475