In [1]:
import torch
import math
import matplotlib.pyplot as plt

import Modules
import Sequential
import Optimizer

def generate_disc_set(nb_sample):
    
    data = torch.empty(nb_sample, 2).uniform_(0, 1)
    labels = data.sub(0.5).pow(2).sum(1).sub(1/(2*math.pi)).sign().add(1).div(2).long()
    
    data_out = data[torch.where(labels==1)]
    data_in = data[torch.where(labels==0)]
    
    plt.figure(figsize=(6,6))
    plt.scatter(data_out[:,0],data_out[:,1])
    plt.scatter(data_in[:,0], data_in[:,1])

    return data, labels

data, target = generate_disc_set(1000)
input1 = data[0:4]
target1 = target[0:4]
m1 = Modules.Linear(2,25)
m2 = Modules.Linear(25,25)
m3 = Modules.Linear(25,25)
m4 = Modules.Linear(25,2)
relu = Modules.ReLu()
MSE = Modules.MSE()

In [15]:
# Train :

nb_epochs = 25
losses = []

for e in range(nb_epochs):
    
    output = relu(m4(relu(m2(relu(m1(data))))))
    loss = MSE(output,target)
    print(loss)

In [16]:
print(m2.param())

[tensor([[-5.0944e-01,  1.3551e-01, -1.9024e-04, -1.3056e-01, -5.5786e-03,
         -2.5049e-01,  2.5344e-01, -6.1906e-02,  3.2406e-02, -1.7856e-01,
         -5.4061e-02,  3.6797e-01,  2.6338e-01,  4.9275e-02, -1.5464e-03,
          7.1241e-02, -1.1831e-01,  3.7610e-01,  3.1718e-02,  8.6412e-02,
          2.0217e-02,  1.9672e-02, -4.3603e-01, -1.3065e-01,  8.5013e-02],
        [ 2.1008e-01, -1.2571e-01,  4.5521e-01,  4.5020e-02, -4.5911e-02,
         -1.1428e-01, -7.5656e-02, -9.8535e-02,  1.1779e-01, -1.0714e-01,
          1.5161e-01, -2.6421e-01, -4.1218e-01, -2.8623e-01, -5.7988e-03,
         -3.9656e-02, -2.4367e-01,  3.3731e-01, -3.9422e-02,  2.5710e-01,
         -7.7596e-02,  6.9042e-02, -2.9073e-02, -1.4491e-01, -2.6884e-03],
        [-6.8019e-03,  1.5937e-01, -2.7828e-01, -8.2101e-02, -3.2697e-02,
         -8.3558e-02, -3.1161e-01, -2.5578e-02,  1.5588e-01, -6.0819e-02,
          4.0372e-01,  1.7340e-01, -1.3393e-01, -1.6414e-01,  1.0238e-02,
          3.5451e-02, -9.3340e-02, 

In [3]:
mseq = Sequential.Sequential(m1,relu,m2,relu)
mseq.members[::-1]

In [18]:
print(mseq.members)
z = mseq.members[::-1]
for index, module in enumerate(z):
    print(index, "Module :",module)
print("\n")
for index, module in enumerate(mseq.members):
    print(index, "Module :",mseq.members[index])
range1=range(4)
for index, number in enumerate(range1):
    print(index,range1[-index-1])

[<Modules.Linear object at 0x000001629235DF08>, <Modules.ReLu object at 0x0000016296B08E48>, <Modules.Linear object at 0x0000016296549908>, <Modules.ReLu object at 0x0000016296B08E48>]
0 Module : <Modules.ReLu object at 0x0000016296B08E48>
1 Module : <Modules.Linear object at 0x0000016296549908>
2 Module : <Modules.ReLu object at 0x0000016296B08E48>
3 Module : <Modules.Linear object at 0x000001629235DF08>


0 Module : <Modules.Linear object at 0x000001629235DF08>
1 Module : <Modules.ReLu object at 0x0000016296B08E48>
2 Module : <Modules.Linear object at 0x0000016296549908>
3 Module : <Modules.ReLu object at 0x0000016296B08E48>
0 3
1 2
2 1
3 0


In [2]:
nb_epochs = 25
mini_batch_size = 200

model = Sequential.Sequential(m1,relu,m2,relu,m3,relu,m4,relu)
output = model(data)
loss = MSE(output,target)
model.zero_grad()
dl_dx = MSE.backward(output,target)
print(dl_dx)
#for index, memory in enumerate(model.memory):
#    print(model.members[index])
#    print(index,": memory size ",memory.size(), "\n", memory,"\n")
#print(len(model.members))

errors = model.backward(dl_dx)
#for e in range(nb_epochs):
#    output = model(input1)
#    loss = MSE(output,target1)
#    model.zero_grad()
#    dl_dx = MSE.backward(output,target1)
#    model.backward(dl_dx)
       
        
        

tensor([[0.0000, 0.3909],
        [0.0000, 0.4666],
        [0.0000, 0.4236],
        ...,
        [0.0000, 0.4817],
        [0.0000, 0.3958],
        [0.0000, 0.4676]])
tensor([0, 0, 1, 0])
tensor([[-2.0000,  0.7818],
        [-2.0000,  0.9333],
        [ 0.0000, -1.1528],
        ...,
        [-2.0000,  0.9633],
        [-2.0000,  0.7916],
        [ 0.0000, -1.0648]])
[<Modules.Linear object at 0x0000020DA8A42848>, <Modules.ReLu object at 0x0000020DA8A5FF08>, <Modules.Linear object at 0x0000020DA37C6908>, <Modules.ReLu object at 0x0000020DA8A5FF08>, <Modules.Linear object at 0x0000020DA7E29488>, <Modules.ReLu object at 0x0000020DA8A5FF08>, <Modules.Linear object at 0x0000020DA423CF08>, <Modules.ReLu object at 0x0000020DA8A5FF08>]
first dl: tensor([[-2.0000,  0.7818],
        [-2.0000,  0.9333],
        [ 0.0000, -1.1528],
        ...,
        [-2.0000,  0.9633],
        [-2.0000,  0.7916],
        [ 0.0000, -1.0648]])
0 <Modules.ReLu object at 0x0000020DA8A5FF08> tensor([[0.0000, 0.3

RuntimeError: output with shape [1, 2] doesn't match the broadcast shape [1000, 2]

In [10]:
a = torch.empty(4,25)
b = torch.empty(4,2)
print(a.t().size())
print(a.t().mm(b).size())

torch.Size([25, 4])
torch.Size([25, 2])


In [6]:
torch.zeros(1,2).size()

torch.Size([1, 2])